package com.gikk.speedment.test.gikk_stream_util;

import com.gikk.speedment.test.gikk_stream_util.db0.gikk_stream_util.users.impl.UsersManagerImpl;
import com.speedment.internal.core.runtime.SpeedmentApplicationLifecycle;
import javax.annotation.Generated;

/**
 * A {@link
 * com.speedment.internal.core.runtime.SpeedmentApplicationLifecycle} class
 * for the {@link com.speedment.config.Project} named gikk_stream_util.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public class GikkStreamUtilApplication extends SpeedmentApplicationLifecycle<GikkStreamUtilApplication> {
    
    public GikkStreamUtilApplication() {
        setSpeedmentApplicationMetadata(new GikkStreamUtilApplicationMetadata());
    }
    
    @Override
    protected void onInit() {
        super.onInit();
        loadAndSetProject();
        put(new UsersManagerImpl(speedment));
    }
}